### ISSUE TITLE
Question - Dynamically subscribe to events

### ISSUE THREAD

**Issue by flaviocordova** [berkesa/moleculer-java#23]
Hi @berkesa 

Is there any way I could programatically subscribe to events instead of hard code them ?
I work with a workflow engine and I wonder if I could create a bridge to wrap moleculer events and send them to the engine..

I guess I could create a single Listener to **  so that it could select which events to keep and which ones to discard, but I'm not sure if this approach would perform well... maybe it could cause some too many events to be received when you just really need a couple of them.

**Comment by berkesa** [comment]
Hi!
In the current version, there is not much opportunity to dynamically add or remove local Event Listeners (local Event Listeners can be added at any time, but they cannot be removed - there is no such function in the `services.moleculer.eventbus.Eventbus` interface). The only way to monitor any Event is what you have written - monitor "**" or all "workflow.*" Events (if the workflow-related events start with the "workflow" prefix). In this way, it is worth narrowing down the set of observed Events because then fewer serialized Events will pass between the Moleculer nodes.

**Comment by flaviocordova** [comment]
When you say local Event Listeners you mean listeners for local events or local listeners for global events (in any node)?

Maybe only being able to add new listeners could help.. How could I do it?

**Comment by berkesa** [comment]
I meant local listeners for global (cluster-wide) events. As I look at the Eventbus API, I don’t think it will be so appropriate for this purpose (for dynamically added Listers). Possibly so that someone derives a custom Eventbus object from the DefaultEventbus superclass and writes the missing functions.

It would be easier to monitor "**" or "workflow.*" events.

**Comment by berkesa** [comment]
Define a custom Eventbus:
```
ServiceBrokerConfig cfg = new ServiceBrokerConfig();
cfg.setEventbus(new CustomEventbus()); // <-- CustomEventbus extends DefaultEventbus
ServiceBroker broker = new ServiceBroker(cfg);
```
but I’m not sure it’s an easy solution
